"""initial schema

Revision ID: dba435d9f009
Revises: 
Create Date: 2026-03-22 11:13:10.573096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba435d9f009'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_briefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submitter_name', sa.String(length=255), nullable=False),
    sa.Column('submitter_email', sa.String(length=255), nullable=False),
    sa.Column('company_or_author_name', sa.String(length=255), nullable=True),
    sa.Column('project_title', sa.String(length=500), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('audience_tags', sa.JSON(), nullable=False),
    sa.Column('genre_tags', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('creative_direction', sa.Text(), nullable=False),
    sa.Column('comp_titles', sa.Text(), nullable=True),
    sa.Column('likes', sa.Text(), nullable=True),
    sa.Column('dislikes', sa.Text(), nullable=True),
    sa.Column('budget_text', sa.String(length=255), nullable=True),
    sa.Column('timeline_text', sa.String(length=255), nullable=True),
    sa.Column('distribution_mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('subscription_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inquiries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_page', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxonomy_terms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('internal_label', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'slug', name='uq_taxonomy_category_slug')
    )
    with op.batch_alter_table('taxonomy_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxonomy_terms_category'), ['category'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('brief_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creative_brief_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_provider', sa.String(length=50), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('refund_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['creative_brief_id'], ['creative_briefs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creative_brief_id')
    )
    op.create_table('concierge_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creative_brief_id', sa.String(length=36), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_provider', sa.String(length=50), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('refund_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['creative_brief_id'], ['creative_briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('privacy', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shared_with', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_covers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('imprint', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('audience_tags', sa.JSON(), nullable=True),
    sa.Column('genre_tags', sa.JSON(), nullable=True),
    sa.Column('visual_tags', sa.JSON(), nullable=True),
    sa.Column('primary_image_asset_id', sa.String(length=36), nullable=False),
    sa.Column('external_book_url', sa.String(length=1000), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['primary_image_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('freelancer_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('is_self_submission', sa.Boolean(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pronouns', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website_links', sa.JSON(), nullable=True),
    sa.Column('resume_asset_id', sa.String(length=36), nullable=True),
    sa.Column('current_locations', sa.JSON(), nullable=True),
    sa.Column('past_locations', sa.JSON(), nullable=True),
    sa.Column('has_agent', sa.Boolean(), nullable=False),
    sa.Column('agent_details', sa.Text(), nullable=True),
    sa.Column('worked_with_prh', sa.Boolean(), nullable=False),
    sa.Column('prh_details', sa.Text(), nullable=True),
    sa.Column('employee_of_prh', sa.Boolean(), nullable=False),
    sa.Column('prh_employee_details', sa.Text(), nullable=True),
    sa.Column('audience_tags', sa.JSON(), nullable=True),
    sa.Column('style_tags', sa.JSON(), nullable=True),
    sa.Column('genre_tags', sa.JSON(), nullable=True),
    sa.Column('image_tags', sa.JSON(), nullable=True),
    sa.Column('uses_ai', sa.Boolean(), nullable=False),
    sa.Column('ai_details', sa.Text(), nullable=True),
    sa.Column('lived_experience_statement', sa.Text(), nullable=True),
    sa.Column('books_excited_about', sa.JSON(), nullable=True),
    sa.Column('profile_statement', sa.Text(), nullable=True),
    sa.Column('approved_for_hire', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('rate_info', sa.JSON(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['review_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('book_cover_contributors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_cover_id', sa.String(length=36), nullable=False),
    sa.Column('freelancer_profile_id', sa.String(length=36), nullable=True),
    sa.Column('contributor_name', sa.String(length=255), nullable=False),
    sa.Column('contributor_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_cover_id'], ['book_covers.id'], ),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('freelancer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'freelancer_profile_id', name='uq_user_favorite')
    )
    op.create_table('feedback_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('freelancer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('project_context', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=False),
    sa.Column('freelancer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'freelancer_profile_id', name='uq_folder_membership')
    )
    op.create_table('legal_contact_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('freelancer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('external_system_id', sa.String(length=255), nullable=True),
    sa.Column('workflow_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('freelancer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('media_asset_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('freelancer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_notes')
    op.drop_table('portfolio_assets')
    op.drop_table('legal_contact_links')
    op.drop_table('folder_memberships')
    op.drop_table('feedback_entries')
    op.drop_table('favorites')
    op.drop_table('book_cover_contributors')
    op.drop_table('freelancer_profiles')
    op.drop_table('book_covers')
    op.drop_table('media_assets')
    op.drop_table('folders')
    op.drop_table('concierge_orders')
    op.drop_table('brief_orders')
    op.drop_table('users')
    with op.batch_alter_table('taxonomy_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxonomy_terms_category'))

    op.drop_table('taxonomy_terms')
    op.drop_table('inquiries')
    op.drop_table('email_subscriptions')
    op.drop_table('creative_briefs')
    # ### end Alembic commands ###
